### ISSUE TITLE
 Crash server for bitsDamageType == DMG_GRENADE

### ISSUE THREAD

**Issue by Limbooc** [81x08/ReAPI-ZMB#2]
> L 12/03/2018 - 14:49:54: [ReAPI] SetHookChainArg: invalid argument type provided.
> L 12/03/2018 - 14:49:54: [AMXX] Displaying debug trace (plugin "zmb_core.amxx", version "0.1.2a")
> L 12/03/2018 - 14:49:54: [AMXX] Run time error 10: native error (native "SetHookChainArg")
> L 12/03/2018 - 14:49:54: [AMXX]    [0] zmb_core.sma::HC_CBasePlayer_TakeDamage_Pre (line 1797)

> ```
switch(bitsDamageType)
> 		{
> 			case DMG_FALL:
> 			{
> 				if(g_bCvar_GetZombieDamageFalling)
> 				{
> 					return HAM_SUPERCEDE;
> 				}
> 			}
> 			case DMG_GRENADE:
> 			{
> 				if(g_infoZombieClass[gp_iClass[iVictim]][CLASS_HEDEFENCE])
> 				{
> 					fDamage *= g_infoZombieClass[gp_iClass[iVictim]][CLASS_HEDEFENCE];
> 					SetHookChainArg(3, ATYPE_FLOAT, fDamage);
> 				}
> 
> 			}
> 		}
```


Server either crashes or shows error log when throwing a zombie grenade

**Comment by Limbooc** [comment]
zmb_classes.ini

```
[Hulk]
	knife_model = "models/v_knife_deadstrike_zombie.mdl"
	player_model = "deadstrike_zombie_v4"
	
	access = "z"
	speed = "225"
	health = "2200"
	gravity = "1.0"
	footsteps = "1"
	knockback = "0.4"
	hedefence = "0.2"
	factor_damage = "1.2"
	regeneration_hp = "25"
	regeneration_hp_min = "450"
	regeneration_delay = "1.0"
[end]
```

**Comment by aratnitsyn** [comment]
Change number "3" on "4" in function
`SetHookChainArg(3, ATYPE_FLOAT, fDamage);`

**Comment by Limbooc** [comment]
Yes, I have already made a change, I close the issues.ty
